cook/urls.py
from django.urls import path

from .views import DishListView, get_new_dish, get_dishes_to_remove

urlpatterns = [
    path('cook/dishlist', DishListView.as_view(), name='dish_list'),
    path('cook/adddish/<int:cook_id>', get_new_dish, name='get_new_dish'),
    path('cook/getdishestoremove/<int:cook_id>', get_dishes_to_remove, name='get_dishes_to_remove' )
]

cuisine_alacarte/urls.py
from django.contrib import admin
from django.urls import path, include, re_path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('register.urls')),
    path('', include('pages.urls')),

    # Using re_path due to reverse lookup error
    re_path('', include(('customer.urls', 'customer'),
                        namespace='customer')),
    re_path('', include(('delivery_person.urls', 'delivery_person'),
                        namespace='delivery_person')),
    re_path('', include(('item.urls', 'item'),
                        namespace='item')),
    re_path('', include(('manager.urls', 'manager'),
                        namespace='manager')),
    re_path('', include(('ratings.urls', 'ratings'),
                        namespace='ratings')),
    re_path('', include(('salesperson.urls', 'salesperson'),
                        namespace='salesperson')),
    re_path('', include(('cook.urls', 'cook'),
                        namespace='cook')),
    re_path('', include(('restaurant.urls', 'restaurant'),
                        namespace='restaurant')),
    # gives access to django log-in/out pages
    path('', include("django.contrib.auth.urls")),

]

customer/urls.py
from django.urls import path

import customer.views as view
from .views import get_dishes_to_order, view_shopping_cart

urlpatterns = [
    path('customer/history', view.CustomerListView.as_view(), name='view_history'),

    path('customer/createorder', get_dishes_to_order, name='get_dishes_to_order'),
    path('customer/shoppingcart', view_shopping_cart, name='view_shopping_cart')

    path('edit/customer/<int:customer_id>', view.EditCustomerType, name = 'edit_customer_type'),

]

manager/urls.py
from django.urls import path

from .views import CustomerListView, EmployeeList, EditPayCook, EditPayDeliveryPerson

urlpatterns = [
    path('manager/customerlist', CustomerListView.as_view(), name='customer_list'),
    path('manager/employeelist', EmployeeList.as_view(), name='employee_list'),
    path('manager/cookpay/<int:cook_id>', EditPayCook, name='cook_salary_change'),
    path('manager/deliverypersonpay/<int:delivery_person_id>', EditPayDeliveryPerson, name='delivery_person_salary_change'),    
]

ratings/urls.py
from django.urls import path

import ratings.views as view

urlpatterns = [
    # Path to rate something
    path('rate/customer/<int:customer_id>', view.RateCustomer, name = 'rate_customer'),
    path('rate/delivery/<int:delivery_id>', view.RateDelivery, name = 'rate_delivery'),
    path('rate/dish/<int:dish_id>', view.RateDish, name = 'rate_dish'),
    path('rate/item/<int:item_id>', view.RateItem, name = 'rate_item'),

    # Below is the paths to view all the different ratings
    path('ratings/Customer/<int:item_id>',
         view.CustomerRatingListView.as_view(), name='customer_rating_list'),
    path('ratings/Delivery/<int:item_id>',
         view.DeliveryRatingListView.as_view(), name='Delivery_rating_list'),
    path('ratings/Dish/<int:item_id>',
         view.DishRatingListView.as_view(), name='dish_rating_list'),
    path('ratings/Item/<int:item_id>',
         view.ItemRatingListView.as_view(), name='item_rating_list'),
]

salesperson/urls.py
from django.urls import path

from .views import PurchaseListView, EditCommission

urlpatterns = [
    path('salesperson/purchaselist',
        PurchaseListView.as_view(), name='purchase_list'),
    path('salesperson/commission/<int:salesperson_id>',
        EditCommission, name='edit_commission'),
]

cook/models.py
from django.db import models
from django.core.validators import MaxValueValidator, MinValueValidator
from app_user.models import User

# Create your models here.


class Cook(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE, null=True)
    first_name = models.CharField(max_length=20)
    last_name = models.CharField(max_length=30)
    ssn = models.CharField(max_length=9)

#   where they work, will reference restaurants table
    restaurant = models.ForeignKey('restaurant.Restaurant', on_delete=models.SET_NULL, null = True)

#   if cook gets warned more than 3 times they get a warning
    warnings = models.PositiveIntegerField(validators = [MaxValueValidator(3)], default = 0)

    # TODO: Set min salary posible
    salary = models.FloatField(validators = [MinValueValidator(0.01)])

    def __str__(self):
        return self.first_name + ' ' + self.last_name

manager/models.py
from django.db import models
from app_user.models import User


class Manager(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE, null=True)
    first_name = models.CharField(max_length=20)
    last_name = models.CharField(max_length=30)
    ssn = models.CharField(max_length=9)
    salary = models.FloatField()

    def __str__(self):
        return self.first_name + ' ' + self.last_name

manager/forms.py
from django import forms
from django.core.validators import MaxValueValidator, MinValueValidator


class ChangePayForm(forms.Form):
    pay = forms.FloatField(
        validators=[MinValueValidator(0.01),],
    )

manager/views.py
from django.shortcuts import render, get_object_or_404
from django.http import HttpResponse, HttpResponseRedirect
from django.template import loader
from django.utils.decorators import method_decorator
from django.contrib.auth.decorators import login_required
from django.views.generic.list import ListView, View

from .models import Manager
from .forms import ChangePayForm

from app_user.models import User
from cook.models import Cook
from customer.models import Customer
from delivery_person.models import DeliveryPerson
from restaurant.models import Restaurant

@method_decorator([login_required], name='dispatch')
class CustomerListView(ListView):
    model = Customer
    template_name = 'manager/customer_list.html'

    def get_queryset(self, **kwargs):
        restaurant = Manager.objects.filter(user=self.request.user.id)[0].restaurant_set.all()[0]
        return restaurant.customer_set.all()


@method_decorator([login_required], name='dispatch')
class EmployeeList(View):

    def get(self, request, *args, **kwargs):
        restaurant = Restaurant.objects.filter(manager=self.request.user.manager.id)[0]
        return render(request, 'manager/employee_list.html', {'restaurant': restaurant})

def EditPayCook(request, cook_id):
    if request.method == 'POST':
        form = ChangePayForm(request.POST)
        if form.is_valid():
            _process_pay_change_cook(
                form.cleaned_data['pay'],
                cook_id
            )
            return HttpResponseRedirect('/manager/employeelist')

    else:
        form = ChangePayForm()

    return render(request, 'manager/edit_pay_form.html', {'form': form})


def _process_pay_change_cook(salary, cook_id):
    cook = Cook.objects.get(id=cook_id)
    cook.salary = salary
    cook.save()

def EditPayDeliveryPerson(request, delivery_person_id):
    if request.method == 'POST':
        form = ChangePayForm(request.POST)
        if form.is_valid():
            _process_pay_change_del(
                form.cleaned_data['pay'],
                delivery_person_id
            )
            return HttpResponseRedirect('/manager/employeelist')

    else:
        form = ChangePayForm()

    return render(request, 'manager/edit_pay_form.html', {'form': form})


def _process_pay_change_del(salary, delivery_person_id):
    delivery_person = DeliveryPerson.objects.get(id=delivery_person_id)
    delivery_person.salary = salary
    delivery_person.save()

manager/templates/manager/customer_list.html
{% extends "pages/home.html" %}

{% block content %}
<ul>
    {% if object_list is not empty %}
    <table border="1" cellspacing="0" cellpadding="8" width="640" align="left">
        <tr>
            <td align='center' nowrap>Name</td>
            <td align='center' nowrap>Type</td>
            <td align='center' nowrap>Orders</td>
            <td align='center' nowrap>Ratings</td>
            <td align='center' nowrap></td>
        </tr>
        <!-- NOTE: for listviews list must be called object_list -->
        {% for customer in object_list %}
        <tr>
            <td align='center' nowrap>{{ customer }}</td>
            <td align='center' nowrap>{{ customer.get_status }} </td>
            <td align='center' nowrap>{{ customer.delivery_set.all | length }}</td>
            {% if customer.rating_set.all  is not empty %}
            <td align='center' nowrap><a href="{% url 'ratings:customer_rating_list' customer.id %}">Ratings</a></td>
            {% else %}
            <td align='center' nowrap>None</td>
            {% endif %}
            {% if customer.customer_type == 0 %}
            <td align='center' nowrap></td>
            {% else %}
            <td align='center' nowrap><a href="{% url 'customer:edit_customer_type' customer.id %}">Edit</a></td>
            {% endif %}
        </tr>
        {% endfor %}
    </table>
    {% else %}
    <p>
        Nothing Here.
    </p>
    {% endif %}
</ul>
{% endblock content %}

manager/templates/manager/edit_pay_form.html
{% extends "pages/home.html" %}
{% load crispy_forms_tags %}

{% block content %}
<form method="POST">
    {% csrf_token %}
    {{ form | crispy}}
    <input type="submit" value="Submit">
</form>
{% endblock content %}

manager/templates/manager/employee_list.html
{% extends "pages/home.html" %}

{% block content %}
<h2 align='center'>Cooks</h2>
{% if restaurant.cook_set.all is not empty %}
<ul>
    <table border="1" cellspacing="0" cellpadding="4" width="700" align="center">
        <tr>
            <td align='center' nowrap>Name</td>
            <td align='center' nowrap>Salary</td>
            <td align='center' nowrap>Dishes</td>
            <!-- <td align='center' nowrap>Score</td> -->
            <td align='center' nowrap>Warnings</td>
        </tr>
        {% for cook in  restaurant.cook_set.all%}
        <tr>
            <td align='center' nowrap>{{ cook }}</td>
            <td align='center' nowrap><a href="{% url 'manager:cook_salary_change' cook.id %}">${{ cook.salary | floatformat:2 }}</a></td>
            <td align='center' nowrap>{{ cook.dish_set.all | length }}</td>
            <!-- <td align='center' nowrap>TODO</td> -->
            <td align='center' nowrap>{{ cook.warnings }}</td>
        </tr>
        {% endfor %}
    </table>
</ul>
{% else %}
<p align=center>No Cooks</p>
{% endif %}

<br></br>
<h2 align='center'>Delivery People</h2>
{% if restaurant.deliveryperson_set.all is not empty %}
<ul>

    <table border="1" cellspacing="0" cellpadding="4" width="700" align="center">
        <tr>
            <td align='center' nowrap>Name</td>
            <td align='center' nowrap>Salary</td>
            <td align='center' nowrap>Deliveries</td>
            <!-- <td align='center' nowrap>Score</td> -->
            <td align='center' nowrap>Warnings</td>
        </tr>
        {% for deliver_person in restaurant.deliveryperson_set.all%}
        <tr>
            <td align='center' nowrap>{{ deliver_person }}</td>
            <td align='center' nowrap><a href="{% url 'manager:delivery_person_salary_change' deliver_person.id %}">${{ deliver_person.salary | floatformat:2 }}</a></td>
            <td align='center' nowrap>{{ deliver_person.delivery_set.all | length }}</td>
            <!-- <td align='center' nowrap>TODO</td> -->
            <td align='center' nowrap>{{ deliver_person.warnings }}</td>
        </tr>
        {% endfor %}
    </table>
</ul>
{% else %}
<p align=center>No Delivery People</p>
{% endif %}
<br></br>

<h2 align='center'>Salespeople</h2>
{% if restaurant.salesperson_set.all is not empty %}
<ul>
    
    <table border="1" cellspacing="0" cellpadding="4" width="700" align="center">
        <tr>
            <td align='center' nowrap>Name</td>
            <td align='center' nowrap>Salary</td>
            <td align='center' nowrap>Commission</td>
            <td align='center' nowrap>Purchases</td>
            <!-- <td align='center' nowrap>Score</td> -->
            <td align='center' nowrap>Warnings</td>
        </tr>
        {% for salesperson in restaurant.salesperson_set.all%}
        <tr>
            <td align='center' nowrap>{{ salesperson }}</td>
            <td align='center' nowrap>${{ salesperson.salary | floatformat:2 }} </td>
            <td align='center' nowrap><a href="{% url 'salesperson:edit_commission' salesperson.id %}">{{ salesperson.commission | floatformat:2 }}</a></td>
            <td align='center' nowrap>{{ salesperson.purchase_set.all | length }}</td>
            <!-- <td align='center' nowrap>TODO</td> -->
            <td align='center' nowrap>{{ salesperson.warnings }}</td>
        </tr>
        {% endfor %}
    </table>
</ul>
{% else %}
<p align=center>No Cooks</p>
{% endif %}

{% endblock content %}