cook/urls.py
from django.urls import path

from .views import DishListView, get_new_dish, get_dishes_to_remove

urlpatterns = [
    path('cook/dishlist', DishListView.as_view(), name='dish_list'),
    path('cook/adddish/<int:cook_id>', get_new_dish, name='get_new_dish'),
    path('cook/getdishestoremove/<int:cook_id>', get_dishes_to_remove, name='get_dishes_to_remove' )
]

cuisine_alacarte/urls.py
from django.contrib import admin
from django.urls import path, include, re_path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('register.urls')),
    path('', include('pages.urls')),

    # Using re_path due to reverse lookup error
    re_path('', include(('customer.urls', 'customer'),
                        namespace='customer')),
    re_path('', include(('delivery_person.urls', 'delivery_person'),
                        namespace='delivery_person')),
    re_path('', include(('item.urls', 'item'),
                        namespace='item')),
    re_path('', include(('manager.urls', 'manager'),
                        namespace='manager')),
    re_path('', include(('ratings.urls', 'ratings'),
                        namespace='ratings')),
    re_path('', include(('salesperson.urls', 'salesperson'),
                        namespace='salesperson')),
    re_path('', include(('cook.urls', 'cook'),
                        namespace='cook')),
    re_path('', include(('restaurant.urls', 'restaurant'),
                        namespace='restaurant')),
    # gives access to django log-in/out pages
    path('', include("django.contrib.auth.urls")),

]

customer/urls.py
from django.urls import path

import customer.views as view
from .views import get_dishes_to_order, view_shopping_cart

urlpatterns = [
    path('customer/history', view.CustomerListView.as_view(), name='view_history'),

    path('customer/createorder', get_dishes_to_order, name='get_dishes_to_order'),
    path('customer/shoppingcart', view_shopping_cart, name='view_shopping_cart')

    path('edit/customer/<int:customer_id>', view.EditCustomerType, name = 'edit_customer_type'),

]

ratings/urls.py
from django.urls import path

import ratings.views as view

urlpatterns = [
    # Path to rate something
    path('rate/customer/<int:customer_id>', view.RateCustomer, name = 'rate_customer'),
    path('rate/delivery/<int:delivery_id>', view.RateDelivery, name = 'rate_delivery'),
    path('rate/dish/<int:dish_id>', view.RateDish, name = 'rate_dish'),
    path('rate/item/<int:item_id>', view.RateItem, name = 'rate_item'),

    # Below is the paths to view all the different ratings
    path('ratings/Customer/<int:item_id>',
         view.CustomerRatingListView.as_view(), name='customer_rating_list'),
    path('ratings/Delivery/<int:item_id>',
         view.DeliveryRatingListView.as_view(), name='Delivery_rating_list'),
    path('ratings/Dish/<int:item_id>',
         view.DishRatingListView.as_view(), name='dish_rating_list'),
    path('ratings/Item/<int:item_id>',
         view.ItemRatingListView.as_view(), name='item_rating_list'),
]

customer/models.py
from django.db import models
from django.utils import timezone
from app_user.models import User

import datetime


class Customer(models.Model):
    """
    Customer model is used for all customers in the cuisine alcarte project.
    Default behavior is to add a visitor upon checkout with and order that was
    completed.
    """

    # Options for the customer type
    CUSTOMER_TYPES = [
        (0, "Visitor"),
        (1, "Registered"),
        (2, "VIP"),
        (3, 'Blacklisted'),
    ]
    user = models.OneToOneField(User, on_delete=models.CASCADE, null=True)
    customer_type = models.CharField(
        max_length=11, choices=CUSTOMER_TYPES, default="VISITOR"
    )
    first_name = models.CharField(max_length=20, blank=True, default="")
    last_name = models.CharField(max_length=20, blank=True, default="")
    customer_email = models.CharField(max_length=100, blank=True, default="")
    address = models.CharField(max_length=100, blank=True, default="NOTSET")

    restaurant = models.ForeignKey(
        "restaurant.Restaurant", on_delete=models.SET_NULL, null=True,
    )
    
    def __str__(self):
        if self.customer_type == 0:
            return str(self.customer_type)

        return self.first_name + " " + self.last_name

    @property
    def get_status(self):
        return Customer.CUSTOMER_TYPES[int(self.customer_type) ][1]


class Order(models.Model):
    STATUSES = [
        (1, "New"),
        (2, "Preparing"),
        (3, "Out for Delivery"),
        (4, "Completed"),
        (5, "Cancelled"),
        (6, "Rated")
    ]

    status = models.PositiveIntegerField(choices=STATUSES, default=1)
    created = models.DateTimeField(default=timezone.now)
    last_updated = models.DateTimeField(default=timezone.now)

    dishes = models.ManyToManyField("item.Dish",)

    restaurant = models.ForeignKey(
        "restaurant.Restaurant", on_delete=models.SET_NULL, null=True,
    )

    customer = models.ForeignKey(
        "customer.Customer", on_delete=models.SET_NULL, null=True,
    )

customer/forms.py
from django import forms

from item.models import Item, Dish
from restaurant.models import Restaurant
from .models import Customer


class CreateOrder(forms.Form):
    dishes = forms.ModelMultipleChoiceField(queryset=Dish.objects.all(), widget=forms.CheckboxSelectMultiple,
                                           required=True, label='Dishes you want to add to your order:')

    fields = ["dishes"]
    #
    # def __init__(self, restaurant, user, *args, **kwargs):
    #     super(CreateOrder, self).__init__(*args, **kwargs)
    #     self.fields['dishes'].queryset = Dish.objects.filter(restaurant=restaurant)


class EditCustomerTypeForm(forms.Form):
    choice = forms.ChoiceField(choices = Customer.CUSTOMER_TYPES)

customer/views.py
from django.shortcuts import render, get_object_or_404
from django.http import HttpResponseRedirect
from django.template import loader
from django.utils.decorators import method_decorator
from django.contrib.auth.decorators import login_required
from django.views.generic.list import ListView
from django.utils import timezone

from .models import Customer, Order
from restaurant.models import Restaurant
from .forms import CreateOrder
from item.models import Dish


from .models import Customer
from .forms import EditCustomerTypeForm

@method_decorator([login_required], name='dispatch')
class CustomerListView(ListView):
    model = Customer
    template_name = 'customer/history_list.html'

    def get_queryset(self, **kwargs):

        user = Customer.objects.get(user=self.request.user.id)
        return user.order_set.all()


def get_dishes_to_order(request):
    form = CreateOrder(request.POST)
    if form.is_valid():
        dishes = form.cleaned_data['dishes']

        # _add_dishes_to_order(dishes)
        return HttpResponseRedirect('/customer/createorder')
    else:
        form = CreateOrder()

    return render(request, 'customer/create_order.html', {'form': form})


def _add_dishes_to_order(dishes):
    new_order = Order.objects.create(status="new", created=timezone.now, last_updated=timezone.now)
    new_order.save()

    for form_dish in dishes:
        # dish = Dish.objects.all()[form_dish.id - 1]
        new_order.dishes.add(form_dish)


def view_shopping_cart(request):
    return render(request, 'customer/shopping_cart.html')


def EditCustomerType(request, customer_id):
    if request.method == 'POST':
        form = EditCustomerTypeForm(request.POST)
        if form.is_valid():
            _process_customer_rating(
                form.cleaned_data['choice'], customer_id)
            return HttpResponseRedirect('/manager/customerlist')

    else:
        form = EditCustomerTypeForm()

    return render(request, 'ratings/rate_form.html', {'form': form})

def _process_customer_rating(choice, customer_id):
    customer = Customer.objects.get(id=customer_id)
    print(Customer.CUSTOMER_TYPES)
    print('\n\n\n\n' + choice)
    customer.customer_type = choice
    customer.save()

customer/templates/customer/create_order.html
{% extends "pages/home.html" %}

{% load crispy_forms_tags %}

{% block content %}
<form method="POST">
    {% csrf_token %}
    {{ form | crispy}}
    <input type="submit" value="Submit">
</form>
{% endblock content %}

customer/templates/customer/edit_customer_form.html
{% extends "pages/home.html" %}
{% load crispy_forms_tags %}

{% block content %}
<form method="POST">
    {% csrf_token %}
    {{ form | crispy}}
    <input type="submit" value="Submit">
</form>
{% endblock content %}

customer/templates/customer/history_list.html
{% extends "pages/home.html" %}
{% load customer_extras %}
{% block content %}
<ul>
    {% if object_list is not empty %}
    <table border="0" cellspacing="0" cellpadding="8" width="640" align="left">
        <tr>
            <td align='center' nowrap>From</td>
            <td align='center' nowrap>Amount</td>
            <td align='center' nowrap># of Items</td>
            <td align='center' nowrap>Rate Dishes</td>
            <td align='center' nowrap>Was Delivered</td>
        </tr>
        <!-- NOTE: for listviews list must be called object_list -->
        {% for order in object_list %}
        <tr>
            <td align='center' nowrap>{{ order.restaurant }}</td>
            <td align='center' nowrap>Secret</td>
            <td align='center' nowrap>{{ order.dishes.all | length }}</td>
           

            {% if order.status == 4 %}
            <td align='center' nowrap><a href = {% url 'ratings:rate_dish' order.id %}>Rate</a></td>
            {% elif order.status < 6 %}
            <td align='center' nowrap>{{ order.get_status_display }}</td>
            {% else %}
            <td align='center' nowrap>Rated</td>
            {% endif %}

            {% if order.delivery and not order.delivery.deliveryrating%}
            <td align='center' nowrap><a href = {% url 'ratings:rate_delivery' order.id %}>Yes</a></td>
            {% elif order.delivery and order.delivery.deliveryrating%}
            <td align='center' nowrap>Rated</td>
            {% else %}
            <td align='center' nowrap>Pickup</td>
            {% endif %}
        </tr>
        {% endfor %}
    </table>
    {% else %}
    <p>
        Nothing Here.
    </p>
    {% endif %}
</ul>
{% texttospeech "customer/history_list.html" %}
{% endblock content %}