cook/urls.py
from django.urls import path

from .views import DishListView, get_new_dish, get_dishes_to_remove

urlpatterns = [
    path('cook/dishlist', DishListView.as_view(), name='dish_list'),
    path('cook/adddish/<int:cook_id>', get_new_dish, name='get_new_dish'),
    path('cook/getdishestoremove/<int:cook_id>', get_dishes_to_remove, name='get_dishes_to_remove' )
]

cuisine_alacarte/urls.py
from django.contrib import admin
from django.urls import path, include, re_path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('register.urls')),
    path('', include('pages.urls')),

    # Using re_path due to reverse lookup error
    re_path('', include(('customer.urls', 'customer'),
                        namespace='customer')),
    re_path('', include(('delivery_person.urls', 'delivery_person'),
                        namespace='delivery_person')),
    re_path('', include(('item.urls', 'item'),
                        namespace='item')),
    re_path('', include(('manager.urls', 'manager'),
                        namespace='manager')),
    re_path('', include(('ratings.urls', 'ratings'),
                        namespace='ratings')),
    re_path('', include(('salesperson.urls', 'salesperson'),
                        namespace='salesperson')),
    re_path('', include(('cook.urls', 'cook'),
                        namespace='cook')),
    re_path('', include(('restaurant.urls', 'restaurant'),
                        namespace='restaurant')),
    # gives access to django log-in/out pages
    path('', include("django.contrib.auth.urls")),

]

customer/urls.py
from django.urls import path

import customer.views as view
from .views import get_dishes_to_order, view_shopping_cart

urlpatterns = [
    path('customer/history', view.CustomerListView.as_view(), name='view_history'),

    path('customer/createorder', get_dishes_to_order, name='get_dishes_to_order'),
    path('customer/shoppingcart', view_shopping_cart, name='view_shopping_cart')

    path('edit/customer/<int:customer_id>', view.EditCustomerType, name = 'edit_customer_type'),

]

restaurant/urls.py
from django.urls import path

from .views import RestaurantListView

urlpatterns = [
    path('restaurant/restaurantlist', RestaurantListView.as_view(), name='restaurant_list'),
]

item/models.py
from django.db import models

from django.core.validators import MaxValueValidator, MinValueValidator


class Item(models.Model):
    name = models.CharField(max_length=40)
    price = models.DecimalField(
        max_digits=6,
        decimal_places=2,
        validators=[MinValueValidator(0.01)],
    )

    restaurant = models.ForeignKey(
        'restaurant.Restaurant', null=True,
        on_delete=models.SET_NULL,
    )

    def __str__(self):
        return self.name


class Dish(models.Model):
    name = models.CharField(max_length=25)
    items = models.ManyToManyField(Item, blank=True)
    price = models.FloatField()

    restaurants = models.ManyToManyField('restaurant.Restaurant')

    # Rating is different than item rating as user rates a dish
    # rating = models.ForeignKey(
    #     'ratings.Rating',
    #     on_delete=models.CASCADE,
    #     blank=True,
    #     null=True,
    # )

    cook = models.ForeignKey(
        'cook.Cook',
        null=True,
        blank=True,
        on_delete=models.SET_NULL,
    )

    def __str__(self):
        return self.name

restaurant/models.py
from django.db import models

# Create your models here.
class Restaurant(models.Model):
    name = models.CharField(max_length=40)
    address = models.CharField(max_length=200)
    manager = models.ForeignKey('manager.Manager', on_delete=models.CASCADE)
    menu = models.ForeignKey('item.Dish', on_delete=models.CASCADE, null=True)
    
    def __str__(self):
        return self.name

restaurant/views.py
from django.shortcuts import render
from django.utils.decorators import method_decorator
from django.contrib.auth.decorators import login_required
from django.views.generic.list import ListView
from django.http import HttpResponseRedirect
from .models import Restaurant

# Create your views here.


class RestaurantListView(ListView):
    model = Restaurant

    # Everyone can see the list of restaurant on the main page
    def get_queryset(self, **kwargs):
        return Restaurant.objects.all()

restaurant/templates/restaurant/restaurant_list.html
{% extends "pages/home.html" %}

{% block content %}
<ul>
    <table border="1" cellspacing="0" cellpadding="8" width="640" align="left">
        <tr>
            <td align='center' nowrap>Restaurant Name</td>
            <td align='center' nowrap>Address</td>
            <td align='center' nowrap>Manager></td>
            <td align='center' nowrap>Menu</td>
            <td align='center' nowrap>Place Order</td>
        </tr>
        <!-- NOTE: for listviews list must be called object_list -->
        {% for restaurant in object_list %}
        <tr>
            <td align='center' nowrap>{{ restaurant.name }}</td>
            <td align='center' nowrap>{{ restaurant.address }}</td>
            <td align='center' nowrap>{{ restaurant.manager }}</td>
            <td align='center' nowrap>
                {% for dish in restaurant.dish_set.all %}
                    {{ dish }} ${{ dish.price }},
                {% endfor %}
            </td>
            <td align='center' nowrap>
                <a href="{% url 'customer:get_dishes_to_order' %}">Order from {{ restaurant.name }}</a>
            </td>
        </tr>
        {% empty %}
        <p>
            Nothing Here.
        </p>
        {% endfor %}
    </table>
</ul>

{% endblock content %}