cook/urls.py
from django.urls import path

from .views import DishListView, get_new_dish, get_dishes_to_remove

urlpatterns = [
    path('cook/dishlist', DishListView.as_view(), name='dish_list'),
    path('cook/adddish/<int:cook_id>', get_new_dish, name='get_new_dish'),
    path('cook/getdishestoremove/<int:cook_id>', get_dishes_to_remove, name='get_dishes_to_remove' )
]

cuisine_alacarte/urls.py
from django.contrib import admin
from django.urls import path, include, re_path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('register.urls')),
    path('', include('pages.urls')),

    # Using re_path due to reverse lookup error
    re_path('', include(('customer.urls', 'customer'),
                        namespace='customer')),
    re_path('', include(('delivery_person.urls', 'delivery_person'),
                        namespace='delivery_person')),
    re_path('', include(('item.urls', 'item'),
                        namespace='item')),
    re_path('', include(('manager.urls', 'manager'),
                        namespace='manager')),
    re_path('', include(('ratings.urls', 'ratings'),
                        namespace='ratings')),
    re_path('', include(('salesperson.urls', 'salesperson'),
                        namespace='salesperson')),
    re_path('', include(('cook.urls', 'cook'),
                        namespace='cook')),
    re_path('', include(('restaurant.urls', 'restaurant'),
                        namespace='restaurant')),
    # gives access to django log-in/out pages
    path('', include("django.contrib.auth.urls")),

]

delivery_person/urls.py
from django.urls import path

from .views import DeliveryListView, get_bid

urlpatterns = [
    path('deliveryperson/deliverylist', DeliveryListView.as_view(), name='delivery_list'),
    path('deliveryperson/bid/<int:purchase_id>', get_bid, name='get_bid')
]

ratings/urls.py
from django.urls import path

import ratings.views as view

urlpatterns = [
    # Path to rate something
    path('rate/customer/<int:customer_id>', view.RateCustomer, name = 'rate_customer'),
    path('rate/delivery/<int:delivery_id>', view.RateDelivery, name = 'rate_delivery'),
    path('rate/dish/<int:dish_id>', view.RateDish, name = 'rate_dish'),
    path('rate/item/<int:item_id>', view.RateItem, name = 'rate_item'),

    # Below is the paths to view all the different ratings
    path('ratings/Customer/<int:item_id>',
         view.CustomerRatingListView.as_view(), name='customer_rating_list'),
    path('ratings/Delivery/<int:item_id>',
         view.DeliveryRatingListView.as_view(), name='Delivery_rating_list'),
    path('ratings/Dish/<int:item_id>',
         view.DishRatingListView.as_view(), name='dish_rating_list'),
    path('ratings/Item/<int:item_id>',
         view.ItemRatingListView.as_view(), name='item_rating_list'),
]

delivery_person/models.py
from django.db import models

from django.core.validators import MaxValueValidator, MinValueValidator
from app_user.models import User
from customer.models import Order


class DeliveryPerson(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE, null=True)
    first_name = models.CharField(max_length=20)
    last_name = models.CharField(max_length=30)
    ssn = models.CharField(max_length=9)
    salary = models.FloatField(
        validators=[MinValueValidator(0.01)],
    )
#   where they work, will reference restaurants table
    restaurant = models.ForeignKey(
        'restaurant.Restaurant',
        null=True,
        on_delete=models.SET_NULL,
        blank=True,
    )

    warnings = models.PositiveIntegerField(
        validators=[MaxValueValidator(3)],
        default=0,
    )

    def __str__(self):
        return self.first_name + ' ' + self.last_name

class Delivery(models.Model):
    STATUSES = [
        (1, 'New'),
        (2, 'Open To Bid'),
        (3, 'Active'),
        (4, 'Completed')
    ]
    status = models.PositiveIntegerField(choices = STATUSES, default = 1)
    bid = models.FloatField(default = -1)

    who_delivered = models.ForeignKey(
        DeliveryPerson,
        on_delete=models.SET_NULL,
        null=True,
        blank=True,
    )

    to_customer = models.ForeignKey(
        'customer.Customer',
        on_delete=models.SET_NULL,
        null=True,
         blank=True,
    )

    purchase = models.OneToOneField(
        Order,
        on_delete=models.SET_NULL,
        null = True,
        blank = True,
    )

    # Notes about order, IE no plastic forks, etc
    notes = models.CharField(
        max_length=100,
        blank=True,
        default='',
    )

delivery_person/forms.py
from django import forms
from django.core.validators import MinValueValidator

class BidForm(forms.Form):
    bid = forms.FloatField(
        validators=[MinValueValidator(0.01)],
    )

delivery_person/views.py
from django.shortcuts import render, get_object_or_404
from django.http import HttpResponseRedirect
from django.template import loader
from django.utils.decorators import method_decorator
from django.contrib.auth.decorators import login_required
from django.views.generic.list import ListView

from .models import DeliveryPerson, Delivery
from .forms import BidForm

@method_decorator([login_required], name='dispatch')
class DeliveryListView(ListView):
    model = Delivery

    def get_queryset(self, **kwargs):
        user = DeliveryPerson.objects.filter(user=self.request.user.id)[0]
        return user.delivery_set.all()


def get_bid(request, purchase_id):
    if request.method == 'POST':
        form = BidForm(request.POST)
        if form.is_valid():
            _process_bid(form.cleaned_data['bid'], purchase_id)
            return HttpResponseRedirect('/deliveryperson/deliverylist')

    # if a GET (or any other method) we'll create a blank form
    else:
        form = BidForm()

    return render(request, 'delivery_person/bid_form.html', {'form': form})


def _process_bid(bid, purchase_id):
    delivery = Delivery.objects.all()[purchase_id - 1]
    delivery.bid = bid
    delivery.status = 2
    delivery.save()

delivery_person/templates/delivery_person/bid_form.html
{% extends "pages/home.html" %}

{% load crispy_forms_tags %}

{% block content %}
<form method="POST">
    {% csrf_token %}
    {{ form | crispy}}
    <input type="submit" value="Submit">
</form>
{% endblock content %}

delivery_person/templates/delivery_person/delivery_list.html
{% extends "pages/home.html" %}

{% block content %}
<ul>
    <table border="0" cellspacing="0" cellpadding="8" width="640" align="left">
        <tr>
            <td align='center' nowrap>Delivery Number</td>
            <td align='center' nowrap>Assigned</td>
            <td align='center' nowrap>Address</td>
            <td align='center' nowrap>Status</td>
            <td align='center' nowrap>Options</td>
        </tr>
        <!-- NOTE: for listviews list must be called object_list -->
        {% for delivery in object_list %}
        <tr>
            <td align='center' nowrap>{{ delivery.id }}</td>
            <td align='center' nowrap>{{ delivery.who_delivered }} </td>
            <td align='center' nowrap>{{ delivery.to_customer.address }}</td>
            <td align='center' nowrap>{{ delivery.get_status_display}}</td>
            
            {% if delivery.status == 1 or delivery.status == 2%}
            <td align='center' nowrap><a href="{% url 'delivery_person:get_bid' delivery.id %}">Bid</a></td>
            {% elif delivery.status == 3 %}
            <td align='center' nowrap><a href='/'>Cancel</a></td>
            {% elif delivery.status == 4 and delivery.rating %}
            <td align='center' nowrap><a href="{% url 'ratings:rate_customer' delivery.to_customer.id %}">Rate</a></td>
            {% else %}
            <td align='center' nowrap>None</td>
            {% endif %}
        </tr>

        {% empty %}
        <tr>
            <td>
                Nothing Here.
            </td>
        </tr>
        {% endfor %}
    </table>
</ul>
{% endblock content %}